#!/usr/bin/bash

export AIB=${AIB:-`pwd`/automotive-image-builder}
export TESTDIR=${TESTDIR:-`pwd`/tests}
export OUTDIR=${OUTDIR:-`pwd`/_testdir}

RES=0

mkdir -p $OUTDIR
export BUILDDIR=$OUTDIR/build
export RUNDIR=$OUTDIR/run

ALL_TESTS=`cd $TESTDIR/integration; echo *.sh`

TESTS=${TESTS:-$ALL_TESTS}
for casefile in $TESTS; do
    echo =========== $casefile ============

    cd $OUTDIR
    rm -rf $RUNDIR
    mkdir $RUNDIR
    cd $RUNDIR

    if ! bash -x -e $TESTDIR/integration/$casefile; then
       echo FAILED
       RES=1
    fi
done

exit $RES
