version: '2'
mpp-vars:
  root_partition:
    mpp-if: use_aboot
    then:
      id: $aboot_partlabel
      name: $aboot_partlabel
      type:
        mpp-eval: "'0FC63DAF-8483-4772-8E79-3D69D8477DE4' if partition_label == 'gpt' else '83'"
      uuid: $rootpart_uuid
    else:
      id: root
      name: root
      type:
        mpp-eval: "'0FC63DAF-8483-4772-8E79-3D69D8477DE4' if partition_label == 'gpt' else '83'"
      uuid: $rootpart_uuid
  sbl_partition:
    id: sbl
    name: sbl
    size: $sblpart_size
    type:
      mpp-eval: "'00000000-0000-0000-0000-000000000000' if partition_label == 'gpt' else '0'"
  efi_partition:
    id: efi
    name: efi
    size: $efipart_size
    type:
      mpp-eval: "'C12A7328-F81F-11D2-BA4B-00A0C93EC93B' if partition_label == 'gpt' else '$efipart_dos_type'"
    uuid: $efipart_uuid
    bootable:
      mpp-eval: efipart_bootable
  boot_partition:
    id: boot
    name: boot
    size: $bootpart_size
    type:
      mpp-eval: "'0FC63DAF-8483-4772-8E79-3D69D8477DE4' if partition_label == 'gpt' else '83'"
    uuid: $bootpart_uuid
  aboot_a_partition:
    id: boot_a
    name: boot_a
    size: $abootpart_size
    type: 20117F86-E985-4357-B9EE-374BC1D8487D # Android boot v2
    uuid: $abootpart_a_uuid
    attrs:
      mpp-eval: active_gpt_attrs
  aboot_b_partition:
    id: boot_b
    name: boot_b
    size: $abootpart_size
    type: 20117F86-E985-4357-B9EE-374BC1D8487D # Android boot v2
    uuid: $abootpart_b_uuid
    attrs:
      mpp-eval: inactive_gpt_attrs
  vbmeta_a_partition:
    id: vbmeta_a
    name: vbmeta_a
    size: $vbmetapart_size
    type: 20117F86-E985-4357-B9EE-374BC1D8487D # Android boot v2
    uuid: $vbmetapart_a_uuid
    attrs:
      mpp-eval: active_gpt_attrs
  vbmeta_b_partition:
    id: vbmeta_b
    name: vbmeta_b
    size: $vbmetapart_size
    type: 20117F86-E985-4357-B9EE-374BC1D8487D # Android boot v2
    uuid: $vbmetapart_b_uuid
    attrs:
      mpp-eval: inactive_gpt_attrs
  base_partitions:
    - mpp-if: use_sblpart
      then:
        mpp-eval: sbl_partition
    - mpp-if: use_efipart
      then:
        mpp-eval: efi_partition
    - mpp-if: use_bootpart
      then:
        mpp-eval: boot_partition
    - mpp-if: use_abootpart
      then:
        mpp-eval: aboot_a_partition
    - mpp-if: use_abootpart
      then:
        mpp-eval: aboot_b_partition
    - mpp-if: use_vbmetapart
      then:
        mpp-eval: vbmeta_a_partition
    - mpp-if: use_vbmetapart
      then:
        mpp-eval: vbmeta_b_partition
  separate_var_partition:
    id: var
    name: var
    size:
      mpp-eval: _varpart_size
    type:
      mpp-eval: "'0FC63DAF-8483-4772-8E79-3D69D8477DE4' if partition_label == 'gpt' else '83'"
    uuid: $varpart_uuid
  separate_qm_var_partition:
    id: qm_var
    name: qm_var
    size:
      mpp-eval: _qm_varpart_size
    type:
      mpp-eval: "'0FC63DAF-8483-4772-8E79-3D69D8477DE4' if partition_label == 'gpt' else '83'"
    uuid: $qm_varpart_uuid
  separate_var_partitions:
    - mpp-if: _use_separate_var and _varpart_size > 0
      then:
        mpp-eval: separate_var_partition
    - mpp-if: _qm_use_separate_var and _qm_varpart_size > 0
      then:
        mpp-eval: separate_qm_var_partition

mpp-define-images:
  - id: image
    size: $image_size
    table:
      uuid: $parttab_uuid
      label: $partition_label
      partitions:
        mpp-join:
          - mpp-eval: base_partitions
          - mpp-if: use_testpart
            then:
              mpp-eval: _test_partitions
          - mpp-eval: extra_parts
          - mpp-eval: separate_var_partitions
          - - mpp-eval: root_partition

pipelines:
  - name: build
    runner: org.osbuild.centos9
    stages:
      - type: org.osbuild.rpm
        inputs:
          packages:
            type: org.osbuild.files
            origin: org.osbuild.source
            mpp-depsolve:
              architecture: $arch
              module-platform-id: $distro_module_id
              baseurl: $distro_baseurl_repo
              repos:
                mpp-join:
                  - mpp-eval: build_repos
                  - mpp-eval: extra_build_repos
              packages:
                mpp-join:
                  - mpp-eval: build_rpms
                  - mpp-eval: extra_build_rpms
                  - mpp-if: use_qm
                    then:
                      - qm
        options:
          gpgkeys:
            - mpp-eval: distro_gpg_keys
          exclude:
            docs: true
      - type: org.osbuild.mkdir
        options:
          paths:
            - path: /usr/share/lorax/templates.d/auto
              parents: true

      - type: org.osbuild.copy
        inputs:
          inlinefile:
            type: org.osbuild.files
            origin: org.osbuild.source
            mpp-embed:
              id: remove
              text:
                remove ${product.name}
        options:
          paths:
            - from:
                mpp-format-string: input://inlinefile/{embedded['remove']}
              to: tree:///usr/share/lorax/templates.d/auto/remove
      - type: org.osbuild.copy
        inputs:
          inlinefile:
            type: org.osbuild.files
            origin: org.osbuild.source
            mpp-embed:
              id: move
              text:
                move ${product.name}
        options:
          paths:
            - from:
                mpp-format-string: input://inlinefile/{embedded['move']}
              to: tree:///usr/share/lorax/templates.d/auto/move
      - type: org.osbuild.copy
        inputs:
          inlinefile:
            type: org.osbuild.files
            origin: org.osbuild.source
            mpp-embed:
              id: symlink
              text:
                symlink ${product.name}
        options:
          paths:
            - from:
                mpp-format-string: input://inlinefile/{embedded['symlink']}
              to: tree:///usr/share/lorax/templates.d/auto/symlink
      - type: org.osbuild.selinux
        options:
          file_contexts:
            mpp-format-string: etc/selinux/{selinux_policy}/contexts/files/file_contexts
          labels:
            /usr/bin/cp: system_u:object_r:install_exec_t:s0
            /usr/bin/tar: system_u:object_r:install_exec_t:s0

  - name: data
    build: name:build
    stages:
      - type: org.osbuild.mkdir
        options:
          paths:
            - path: /etc
            - path: /etc/selinux
      - type: org.osbuild.copy
        inputs:
          inlinefile:
            type: org.osbuild.files
            origin: org.osbuild.source
            mpp-embed:
              id: passwd
              text: $base_passwd
          inlinefile2:
            type: org.osbuild.files
            origin: org.osbuild.source
            mpp-embed:
              id: group
              text: $base_group
          inlinefile3:
            type: org.osbuild.files
            origin: org.osbuild.source
            mpp-embed:
              id: selinux.conf
              text: $selinux_conf
        options:
          paths:
            - from:
                mpp-format-string: input://inlinefile/{embedded['passwd']}
              to: tree:///etc/passwd
            - from:
                mpp-format-string: input://inlinefile2/{embedded['group']}
              to: tree:///etc/group
            - from:
                mpp-format-string: input://inlinefile3/{embedded['selinux.conf']}
              to: tree:///etc/selinux/config
